### ISSUE TITLE
Music sometimes doesn't stop when combat ends.

### ISSUE THREAD

**Issue by Alceris** [Wehavecookies56/Kingdom-Keys-Re-Coded#11]
Pretty self-explanatory title. Sometimes when I leave a battle, the custom battle music just keeps going until the end of the sound file. It seems to happen most commonly with "Happy Holidays!"

**Comment by Wehavecookies56** [comment]
Wow funny that you literally just posted this issue just as I found out about this myself. Anyway the music is definitely not perfect I'll look into it. I think the "Happy Holidays!" issue is something to do with the "!" in the title.

**Comment by Alceris** [comment]
It seems that it actually only happens with "Happy Holidays!" so I just deleted it from my copy of the resource pack for now. I didn't really like it much anyway.
