### ISSUE TITLE
All Drive Forms except Anti Form don't animate holding an item or swinging.

### ISSUE THREAD

**Issue by Alceris** [Wehavecookies56/Kingdom-Keys-Re-Coded#12]
Again, there's not much more to really say on the matter, the extra parts added by the Drive Forms don't take into account holding an item or swinging things around. Oh, right, and the dark overlay from Anti Form gets slightly detached if you sneak.

**Comment by Wehavecookies56** [comment]
Mostly fixed by 59b3e52

**Comment by Alceris** [comment]
That commit was apparently 5 days ago, so it clearly hasn't done anything about what I mentioned.

**Comment by Wehavecookies56** [comment]
Yes it has, the only thing it didn't fix was the sneaking.

**Comment by Alceris** [comment]
How could it have fixed a bug 5 days ago that I am currently experiencing?

**Comment by Wehavecookies56** [comment]
Because I fixed it after I had built the current version of the mod

**Comment by Alceris** [comment]
Oh, that makes sense, then.

**Comment by Wehavecookies56** [comment]
This is now fixed as of e780127
