### ISSUE TITLE
Can you add enemies?

### ISSUE THREAD

**Issue by Kevadroz** [Wehavecookies56/Kingdom-Keys-Re-Coded#13]
Can you add some enemies, like heartless, nobodies...
Because a survival isn't so funny without any enemy, and the mod is likely designed to use in survival.

Aren't any mod that adds enemies from Kingdom Hearts games :(

**Comment by Abelatox** [comment]
They will be comming a bit later.

**Comment by Kevadroz** [comment]
ok :)
