### ISSUE TITLE
caused invalid loot table bug. stopped server from starting. 

### ISSUE THREAD

**Issue by kain184** [Wehavecookies56/Kingdom-Keys-Re-Coded#18]
[fml-server-latest.txt](https://github.com/Wehavecookies56/Kingdom-Keys-Re-Coded/files/387488/fml-server-latest.txt)
after removing mod server started properly

**Comment by Wehavecookies56** [comment]
By the looks of it there is another mod which is removing the main loot pool from some of the loot tables. What I'll do is check whether the main loot pool exists, if it doesn't, create a new pool.

**Comment by Wehavecookies56** [comment]
This should be fixed now since 2ee571d
