### ISSUE TITLE
Keys glitch out after first attack on an entity

### ISSUE THREAD

**Issue by Nattehine** [Wehavecookies56/Kingdom-Keys-Re-Coded#39]
On version 0.8.2.1, with Forge version 12.18.1.2092, keys turn into a textureless 3D block after first attack on an entity and stays like that. All keys look fine until you hit something.

**Comment by Wehavecookies56** [comment]
Are you using any other mods?

**Comment by Nattehine** [comment]
I am currently using a custom modpack. I apologize for the long list in advance. 
The mods included are:
- backpack-3.0.0-1.10.2
- Baubles-1.9.4-1.2.1.0
- BetterFoliage-MC1.10-2.1.0
- BiomesOPlenty-1.10.2-5.0.0.2068-universal
- Botania-unofficial.r1.8-321
- BuildingBricks-1.10.2-2.0.12
- Chameleon-1.10-2.1.7
- chiselsandbits-12.1
- ColossalChests-1.9.4-1.3.10
- CoralReef-1.2
- CraftingCraft_1.10.2-4.1.6
- CyclopsCore-1.9.4-0.7.7
- EbonArts-v2.4.7a-mc1.10.2
- EvilCraft-1.10.2-0.10.11
- exnihiloomnia-1.0.4
- ExtraBitManipulation-1.10.2-2.1.0
- FastLeafDecay-v11
- GraveStone Mod 1.5.5
- immcraft-1.9.4-1.1.7
- inventorypets-1.10-1.4.8.1
- jei_1.10.2-3.9.0.244
- journeymap-1.10.2-5.2.4-unlimited
- JustEnoughResources-1.10.2-0.4.8.48
- Kingdom Keys Re Coded-1.10.2-0.8.2-31-universal
- Levels-1.10.2-r4.1.3
- Lots of Food-1.12.0
- malisisblocks-1.9.4-4.0.1
- malisiscore-1.9.4-4.1.1
- malisisdoors-1.9.4-5.0.3
- Mantle-1.10.2-1.0.0
- MCMultiPart-1.2.1-universal
- multistorage-1.10.0-1.2.2
- mysticalagriculture-1.2.2
- NomadicTents[1.10.2]-7.01
- Pam's HarvestCraft 1.9.4-1.10.2b
- Pam's Simple Recipes 1.9.4-1.10.2a
- ProjectE-1.10.2-PE1.0.6B
- RebornCore-1.10.2-2.7.1.38-universal
- shetiphiancore-1.10.0-3.3.0
- SoulShards-TOW-1.10.2-2.6.3-43
- StacksOnStacks2-1.1.4
- StorageDrawers-1.10.2-3.2.6
- supersticksword-0.3.0.0
- TConstruct-1.10-2.3.3a
- TechReborn-1.10.2-1.4.3.52-universal
- terraqueous-1.10.0-1.2.5
- thutcore-1.9.4-3.3.2
- thuttech-3.0.9
- Tinkers' Addons-1.10.x-1.0.3
- TIS-3D-MC1.10-0.9.0.1
- torohealth-1.10.2-1
- Wawla-1.10.2-2.3.0.203
- Waystones_1.10.2-2.0.5
- VeinMiner-0.34.1-1.9r571+73be663
- WorldEditCuiFe-v1.0.4-mf-1.10.2-12.18.1.2026
- worldedit-forge-mc1.10.2-6.1.4-dist

I've already tried removing all the mods that _I know_ have their own renderers which are:
- BetterFoliage-MC1.10-2.1.0
- malisisblocks-1.9.4-4.0.1
- malisiscore-1.9.4-4.1.1
- malisisdoors-1.9.4-5.0.3
- MCMultiPart-1.2.1-universal
- multistorage-1.10.0-1.2.2
- StacksOnStacks2-1.1.4

I'll test this further and try to pinpoint the mod that is causing this and get back to you.

**Comment by Wehavecookies56** [comment]
Try removing Levels, someone else on the MC Forums had the same issue. I'll look into why this is happening with the mod though.

**Comment by Nattehine** [comment]
Phew, you just saved me a bunch of time! I can confirm that yes, it is indeed Levels causing the keys to turn into a textureless block. 
I forgot to mention that they still function as a weapon, the just appear to be a block.
