### ISSUE TITLE
unable to play : (

### ISSUE THREAD

**Issue by MooCowGal** [Wehavecookies56/Kingdom-Keys-Re-Coded#42]
every time I start a game , Im plopped down on the circle and nothing happens... till I leave, at that point I am then prompted to pick my destiny.. but cant since I cant get back?

**Comment by MooCowGal** [comment]
also there are no items on the pedestals?, it says open the menu and choose but theres no interface to choose a weapon

**Comment by MooCowGal** [comment]
also why do i start with a wooden keyblade

**Comment by Wehavecookies56** [comment]
This is not what issues are for. When you start just leave through the door as right now you do not need to choose a weapon, the next version will have that. Everyone gets a wooden keyblade at the start
