### ISSUE TITLE
Spawning first time in empty void

### ISSUE THREAD

**Issue by KamiSami** [Wehavecookies56/Kingdom-Keys-Re-Coded#47]
Title.. Pretty much this happens, i fall in void to death, though the world is not new, i have no clue can that be the issue.. This happens in latest 1.10.2 version, no clue if this will get fixed or not, or if this even is fault of the mod, could be compability issue..
Using forge-12-18-3-2511

And using following mods:
Applied Energistics 2
Bad Wither No Cookie - Reloaded
Baubles
Bed Bugs
Bookshelf
Botania+r1.9-341
Chameleon
Chisel
CodeChicken Core 1.8.+
CodeChicken Lib 1.8.+
CoFH Core
CompatLayer
ConnectedTexturesMod
Dark Utilities
DrCyano's Lootable Bodies
DynamicSurroundings-1.10.2-3.4.9.4
Electroblob's Wizardry
Ender IO
EnderCore
Extra Utilities
Fast Leaf Decay
Hwyla
iChunUtil
Immersive Engineering
JourneyMap
Just Enough Items (JEI)
Kingdom Keys Re:Coded
LLibrary
Lycanites Mobs
MalisisCore
MalisisDoors
MalisisSwitches
McJtyLib
Mob Disemberment
Modular Powersuits
More Player Models
Mowzie's Mobs
Not Enough Items 1.8.+
Random Things
Reliquary v1.3
RFTools
Storage Drawers
Thaumcraft
Thaumic+Insanity+1.10.2-1.2
Thermal Dynamics
Thermal Expansion
Thermal Foundation

**Comment by KamiSami** [comment]
Also should note that i tried delete the dimension and regardless, it was void

**Comment by KamiSami** [comment]
There's also a lot more bugs like a lot missing textures, i am guessing there might be incompability, and some things dont play very well

**Comment by MikeTheDigiGoia** [comment]
The reason for this is, you will realise with the music installed, the Sanctuary of Awakening plays, your first spawning in the "Sanctuary of Awakening" dimension which isn't implemented yet
