### ISSUE TITLE
offhand item changes not pushed to client

### ISSUE THREAD

**Issue by Jackiecrazy** [Wehavecookies56/Kingdom-Keys-Re-Coded#50]
I'm not sure about the exact mechanics, but when unsummoning the keyblade the offhand item disappears and is unusable until you take some drastic measures, which in my case entails opening the baubles page to force refresh my inventory.

**Comment by Jackiecrazy** [comment]
also, for some strange reason unbreaking can be applied to keyblades even though they're unbreakable.

**Comment by npcorey** [comment]
The item is still there when you summon it back. For now, you can click on the slot to force it to refresh and grab it.

**Comment by LordofTheBlue** [comment]
you can also just swap the item back to the hot bar as it still exists and it will be usable again
