### ISSUE TITLE
Heartless do not spawn

### ISSUE THREAD

**Issue by SpringsTS** [Wehavecookies56/Kingdom-Keys-Re-Coded#56]
Hello,

While Moogles spawn regularly during day, I never saw any Heartless during night, only Minecraft monsters.
In Creative, I found the eggs and manually spawned Heartless act and move correctly, but there is no automatic spawn.

The problem occurs on a fresh Minecraft install, no other mod than Forge and Kingdom Keys.

Minecraft version: 1.12.2
Forge version: 14.23.5.2838 (latest version for 1.12)

Thank you in advance for your solutions.

**Comment by Wynd** [comment]
Hi,

The heartless are supposed to spawn only after you kill the ender dragon, they will spawn during the day as well from what I remember, same applies for Nobodies.

**Comment by SpringsTS** [comment]
Thank you a lot for your answer, and indeed I didn't defeat the Enderdragon yet, so it's okay!
