### ISSUE TITLE
how to open b3d files?

### ISSUE THREAD

**Issue by ghost** [Wehavecookies56/Kingdom-Keys-Re-Coded#63]
I used the blend with addons, Ultimate Unwrap 3D, Blitz3D, and etc., and I couldn't open this file, what should I do?

**Comment by Wehavecookies56** [comment]
I had the same issue when forge first implemented support for other model formats post 1.8 b3d was the only format supported which one of the devs made a blender export plugin for, but made no way to import them. However assimp viewer can open and convert b3ds to other formats.

**Comment by ghost** [comment]
may I know why did you choose the b3d format?

**Comment by Wehavecookies56** [comment]
because at the time forge did not support obj

**Comment by ghost** [comment]
did you reverse engineer the KHs to rebuild the 3d model?

**Comment by Wehavecookies56** [comment]
I just used tools that people made to extract and convert the assets from the games. 
Just wondering why do you need to open the files?

**Comment by ghost** [comment]
I really like the pixie petal, and I wanna 3d print it.
may I know the tools' name?

**Comment by Wehavecookies56** [comment]
Ah if that's all you need we've converted all the models to obj in the new version of Kingdom Keys [here](https://github.com/Wehavecookies56/Kingdom-Keys/blob/master/src/main/resources/assets/kingdomkeys/models/item/keyblade/pixiepetal.obj)

**Comment by ghost** [comment]
Thank you so much.
I also need the tool to extract and convert the assets from the games.
May I know the tools` name?

**Comment by Wehavecookies56** [comment]
BBS Modding Station to extract the files from the dat files from the iso then use noesis with the bbs plugin to view and convert them
