### ISSUE TITLE
Add Capes

### ISSUE THREAD

**Issue by p0wer0n** [Wehavecookies56/Kingdom-Keys-Re-Coded#7]
You need to add capes back. The DevCapes mod has been updated for 1.8!

**Comment by p0wer0n** [comment]
Link: https://github.com/mmdanggg2/DeveloperCapes/tree/cf21b2dcbfe44fbac62e98dc7c6595efd4419da0

**Comment by Wehavecookies56** [comment]
Thanks! They have been added 94687b7d4ee8a791497bf5a90eac59a38d70ce60
