### ISSUE TITLE
I have a question about the capes.

### ISSUE THREAD

**Issue by p0wer0n** [Wehavecookies56/Kingdom-Keys-Re-Coded#8]
How exactly did you implement the DeveloperCapes mod into 1.8. I can only get the capes to show in eclipse, and not with a compiled version of a mod.

**Comment by Wehavecookies56** [comment]
I actually didn't realise that was happening. Thanks for notifying me of that. I have fixed this issue in my latest commit 5070700125bc08742063ce07bff684063c3687cd If you look at my changes to StaticCape It now looks for both the de-obfuscated obfuscated name for the fields for reflection.

**Comment by p0wer0n** [comment]
Also, can I have a cape for helping? My IGN is jrd. You can choose the design,

**Comment by Wehavecookies56** [comment]
Sure! I'll add you to the json, Also wow you got a short username.
